destination_index:
    path:     /
    defaults: { _controller: "RandoBackBundle:Destination:index" }
    methods:  GET

destination_show:
    path:     /{id}/show
    defaults: { _controller: "RandoBackBundle:Destination:show" }
    methods:  GET

destination_new:
    path:     /new
    defaults: { _controller: "RandoBackBundle:Destination:new" }
    methods:  [GET, POST]

destination_edit:
    path:     /{id}/edit
    defaults: { _controller: "RandoBackBundle:Destination:edit" }
    methods:  [GET, POST]

destination_delete:
    path:     /{id}/delete
    defaults: { _controller: "RandoBackBundle:Destination:delete" }
    methods:  DELETE
