# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
# app/config/security.yml
security:
    providers:
            fos_userbundle:
                id: fos_user.user_provider.username

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
            Rando\BackBundle\Entity\Utilisateur: bcrypt

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path:             fos_user_security_login
                check_path:             fos_user_security_check
#                csrf_token_generator:
                default_target_path:            /app
            logout:
                        path: fos_user_security_logout
                        target: /
            anonymous:    true


    access_control:
        - { path: ^/app/ , role: ROLE_USER }
        - { path: ^/back/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_USER: ROLE_USER

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
