<?php

namespace Rando\BackBundle\Repository;

/**
 * DestinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinationRepository extends \Doctrine\ORM\EntityRepository
{
}
