<?php

namespace Rando\BackBundle\Repository;

/**
 * gallerieProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gallerieProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
