<?php

namespace Rando\BackBundle\Repository;

/**
 * gallerieEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gallerieEventRepository extends \Doctrine\ORM\EntityRepository
{
}
